//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Numtema_Gestion_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Rappel = new HashSet<Rappel>();
            this.Réclamation = new HashSet<Réclamation>();
            this.Relance = new HashSet<Relance>();
        }
    
        public int ID_Client { get; set; }
        public string Nom { get; set; }
        public string Prénom { get; set; }
        public string Ville { get; set; }
        public string Numéro_de_Téléphone { get; set; }
        public string EMail { get; set; }
        public Nullable<System.DateTime> Date_d_enregistrement { get; set; }
        public string Description { get; set; }
        public Nullable<int> Nombre_de_Relance { get; set; }
        public Nullable<int> ID_TypeClient { get; set; }
    
        public virtual TypeClient TypeClient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rappel> Rappel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Réclamation> Réclamation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relance> Relance { get; set; }
    }
}
