//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Numtema_Gestion_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historique
    {
        public int ID_Historique { get; set; }
        public Nullable<int> ID_Relance { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Relance Relance { get; set; }
    }
}
