//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Numtema_Gestion_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Relance()
        {
            this.Historique = new HashSet<Historique>();
        }
    
        public int ID_Relance { get; set; }
        public Nullable<int> ID_Client { get; set; }
        public Nullable<System.DateTime> Date_de_Relance { get; set; }
        public string Description { get; set; }
        public Nullable<int> Numéro_Relance { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historique> Historique { get; set; }
    }
}
